FROM node:24-bookworm-slim AS base

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends libc6 && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
COPY turbo.json ./
COPY tsconfig.base.json ./
COPY apps ./apps
COPY packages ./packages

RUN npm install

CMD ["npm", "run", "start", "--workspace", "@icat/jobs"]
