FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
  default-mysql-client \
  postgresql-client \
  tar \
  gzip \
  curl \
  msmtp-mta \
  mutt \
  bash \
  tzdata \
  rclone \
  ca-certificates \
  && rm -rf /var/lib/apt/lists/*

COPY scripts/backup.sh /usr/local/bin/backup.sh
RUN chmod +x /usr/local/bin/backup.sh

ENTRYPOINT ["/usr/local/bin/backup.sh"]
