FROM node:latest-alpine AS base

FROM base AS builder
RUN apk update
RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY . .

RUN npx turbo prune @icat/web --docker

FROM base AS installer
RUN apk update
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY --from=builder /app/out/json/ ./
RUN npm ci

COPY --from=builder /app/tsconfig.base.json ./tsconfig.base.json
COPY --from=builder /app/out/full/ ./
COPY --from=builder /app/.env ./.env

RUN npm run build

FROM base AS runner
WORKDIR /app

RUN addgroup --system --gid 1001 irfancarsandtours
RUN adduser --system --uid 1001 irfan
USER irfan

COPY --from=installer --chown=irfan:irfancarsandtours /app/apps/web/.next/standalone ./

ENV PORT=3000
ENV HOSTNAME=0.0.0.0
ENV NODE_OPTIONS=--max-old-space-size=384
ENV NODE_ENV=production

EXPOSE 3000

CMD ["node", "apps/web/server.js"]
